## Part 1 - Data Conditioning

### Import Libraries

In [1]:
import polars as pl

In [2]:
# Set the streaming engine as the default for all future operations
pl.Config.set_engine_affinity("streaming")
# Show all rows
pl.Config.set_tbl_rows(-1)

polars.config.Config

### Load Data

In [3]:
transaction_data = pl.scan_csv(
    "../data/LI-Large_Trans.csv"
)

In [4]:
transaction_data.collect_schema()

Schema([('Timestamp', String),
        ('From Bank', Int64),
        ('Account', String),
        ('To Bank', Int64),
        ('Account_duplicated_0', String),
        ('Amount Received', Float64),
        ('Receiving Currency', String),
        ('Amount Paid', Float64),
        ('Payment Currency', String),
        ('Payment Format', String),
        ('Is Laundering', Int64)])

In [5]:
transaction_data.head(5).collect()

shape: (5, 11)
┌────────────┬───────────┬───────────┬─────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Timestamp  ┆ From Bank ┆ Account   ┆ To Bank ┆ … ┆ Amount    ┆ Payment   ┆ Payment   ┆ Is Launde │
│ ---        ┆ ---       ┆ ---       ┆ ---     ┆   ┆ Paid      ┆ Currency  ┆ Format    ┆ ring      │
│ str        ┆ i64       ┆ str       ┆ i64     ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆           ┆           ┆         ┆   ┆ f64       ┆ str       ┆ str       ┆ i64       │
╞════════════╪═══════════╪═══════════╪═════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2022/08/01 ┆ 20        ┆ 800104D70 ┆ 20      ┆ … ┆ 8095.07   ┆ US Dollar ┆ Reinvestm ┆ 0         │
│ 00:15      ┆           ┆           ┆         ┆   ┆           ┆           ┆ ent       ┆           │
│ 2022/08/01 ┆ 3196      ┆ 800107150 ┆ 3196    ┆ … ┆ 7739.29   ┆ US Dollar ┆ Reinvestm ┆ 0         │
│ 00:18      ┆           ┆           ┆         ┆   ┆           ┆           ┆ ent       ┆           │
│ 2022/08/01 ┆ 1208      ┆ 80010E430 ┆ 1208    ┆ … ┆ 2654.22   ┆ US Dollar ┆ Reinvestm ┆ 0         │
│ 00:23      ┆           ┆           ┆         ┆   ┆           ┆           ┆ ent       ┆           │
│ 2022/08/01 ┆ 3203      ┆ 80010EA80 ┆ 3203    ┆ … ┆ 13284.41  ┆ US Dollar ┆ Reinvestm ┆ 0         │
│ 00:19      ┆           ┆           ┆         ┆   ┆           ┆           ┆ ent       ┆           │
│ 2022/08/01 ┆ 20        ┆ 800104D20 ┆ 20      ┆ … ┆ 9.72      ┆ US Dollar ┆ Reinvestm ┆ 0         │
│ 00:27      ┆           ┆           ┆         ┆   ┆           ┆           ┆ ent       ┆           │
└────────────┴───────────┴───────────┴─────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [6]:
# Number of rows
transaction_data.select(
    pl.len().alias("num_transactions")
).collect()

shape: (1, 1)
┌──────────────────┐
│ num_transactions │
│ ---              │
│ u32              │
╞══════════════════╡
│ 176066557        │
└──────────────────┘

In [7]:
# Check unique values for "Is Laundering"
transaction_data.select(
    "Is Laundering"
).unique().collect()

shape: (2, 1)
┌───────────────┐
│ Is Laundering │
│ ---           │
│ i64           │
╞═══════════════╡
│ 0             │
│ 1             │
└───────────────┘

### Condition Data

#### Convert Timestamp from String into Datetime

In [8]:
# Create a derived column for timestamp (str -> timestamp)
transaction_data = transaction_data.with_columns(
    pl.col("Timestamp")
      .str.to_datetime("%Y/%m/%d %H:%M")
      .alias("Timestamp")
)

In [9]:
transaction_data.select(
    pl.col("Timestamp").min().alias("start_date"),
    pl.col("Timestamp").max().alias("end_date")
).collect()

shape: (1, 2)
┌─────────────────────┬─────────────────────┐
│ start_date          ┆ end_date            │
│ ---                 ┆ ---                 │
│ datetime[μs]        ┆ datetime[μs]        │
╞═════════════════════╪═════════════════════╡
│ 2022-08-01 00:00:00 ┆ 2023-01-12 10:18:00 │
└─────────────────────┴─────────────────────┘

#### Reduce Dataset

In [10]:
daily_transactions = (
    transaction_data
    .group_by(
        pl.col("Timestamp").dt.date().alias("Date")
    )
    .agg(
        pl.len().alias("Transactions")
    )
    .sort("Date")
    .collect()
)

daily_transactions

shape: (164, 2)
┌────────────┬──────────────┐
│ Date       ┆ Transactions │
│ ---        ┆ ---          │
│ date       ┆ u32          │
╞════════════╪══════════════╡
│ 2022-08-01 ┆ 4377581      │
│ 2022-08-02 ┆ 1894426      │
│ 2022-08-03 ┆ 1891657      │
│ 2022-08-04 ┆ 1890988      │
│ 2022-08-05 ┆ 2957130      │
│ 2022-08-06 ┆ 813056       │
│ 2022-08-07 ┆ 814101       │
│ 2022-08-08 ┆ 1891591      │
│ 2022-08-09 ┆ 1890247      │
│ 2022-08-10 ┆ 1890146      │
│ 2022-08-11 ┆ 1889967      │
│ 2022-08-12 ┆ 2568302      │
│ 2022-08-13 ┆ 814055       │
│ 2022-08-14 ┆ 812269       │
│ 2022-08-15 ┆ 1892821      │
│ 2022-08-16 ┆ 1891495      │
│ 2022-08-17 ┆ 1891691      │
│ 2022-08-18 ┆ 1891396      │
│ 2022-08-19 ┆ 2958169      │
│ 2022-08-20 ┆ 814803       │
│ 2022-08-21 ┆ 813530       │
│ 2022-08-22 ┆ 1891747      │
│ 2022-08-23 ┆ 1891491      │
│ 2022-08-24 ┆ 1890017      │
│ 2022-08-25 ┆ 1892593      │
│ 2022-08-26 ┆ 2567772      │
│ 2022-08-27 ┆ 812853       │
│ 2022-08-28 ┆ 813840       │
│ 2022-08-29 ┆ 1892065      │
│ 2022-08-30 ┆ 1890812      │
│ 2022-08-31 ┆ 4206039      │
│ 2022-09-01 ┆ 1892319      │
│ 2022-09-02 ┆ 2957375      │
│ 2022-09-03 ┆ 815386       │
│ 2022-09-04 ┆ 812832       │
│ 2022-09-05 ┆ 1894624      │
│ 2022-09-06 ┆ 1892344      │
│ 2022-09-07 ┆ 1891555      │
│ 2022-09-08 ┆ 1892299      │
│ 2022-09-09 ┆ 2568845      │
│ 2022-09-10 ┆ 814162       │
│ 2022-09-11 ┆ 814200       │
│ 2022-09-12 ┆ 1892539      │
│ 2022-09-13 ┆ 1892387      │
│ 2022-09-14 ┆ 1892965      │
│ 2022-09-15 ┆ 1891778      │
│ 2022-09-16 ┆ 2958501      │
│ 2022-09-17 ┆ 813686       │
│ 2022-09-18 ┆ 813562       │
│ 2022-09-19 ┆ 1892470      │
│ 2022-09-20 ┆ 1892491      │
│ 2022-09-21 ┆ 1893537      │
│ 2022-09-22 ┆ 1892604      │
│ 2022-09-23 ┆ 2568608      │
│ 2022-09-24 ┆ 813779       │
│ 2022-09-25 ┆ 814586       │
│ 2022-09-26 ┆ 1891428      │
│ 2022-09-27 ┆ 1891106      │
│ 2022-09-28 ┆ 1891017      │
│ 2022-09-29 ┆ 1891793      │
│ 2022-09-30 ┆ 5267847      │
│ 2022-10-01 ┆ 816642       │
│ 2022-10-02 ┆ 813867       │
│ 2022-10-03 ┆ 1892387      │
│ 2022-10-04 ┆ 1892169      │
│ 2022-10-05 ┆ 1891281      │
│ 2022-10-06 ┆ 1891587      │
│ 2022-10-07 ┆ 2569213      │
│ 2022-10-08 ┆ 814049       │
│ 2022-10-09 ┆ 815663       │
│ 2022-10-10 ┆ 1890451      │
│ 2022-10-11 ┆ 1890872      │
│ 2022-10-12 ┆ 1891654      │
│ 2022-10-13 ┆ 1891172      │
│ 2022-10-14 ┆ 2956404      │
│ 2022-10-15 ┆ 812499       │
│ 2022-10-16 ┆ 815246       │
│ 2022-10-17 ┆ 1890916      │
│ 2022-10-18 ┆ 1890654      │
│ 2022-10-19 ┆ 1891540      │
│ 2022-10-20 ┆ 1890010      │
│ 2022-10-21 ┆ 2568707      │
│ 2022-10-22 ┆ 815445       │
│ 2022-10-23 ┆ 814191       │
│ 2022-10-24 ┆ 1891308      │
│ 2022-10-25 ┆ 1890227      │
│ 2022-10-26 ┆ 1889484      │
│ 2022-10-27 ┆ 1889923      │
│ 2022-10-28 ┆ 2952853      │
│ 2022-10-29 ┆ 815539       │
│ 2022-10-30 ┆ 3175032      │
│ 2022-10-31 ┆ 1897143      │
│ 2022-11-01 ┆ 1891658      │
│ 2022-11-02 ┆ 1890072      │
│ 2022-11-03 ┆ 1889162      │
│ 2022-11-04 ┆ 2566993      │
│ 2022-11-05 ┆ 812985       │
│ 2022-11-06 ┆ 355          │
│ 2022-11-07 ┆ 284          │
│ 2022-11-08 ┆ 315          │
│ 2022-11-09 ┆ 301          │
│ 2022-11-10 ┆ 262          │
│ 2022-11-11 ┆ 267          │
│ 2022-11-12 ┆ 214          │
│ 2022-11-13 ┆ 271          │
│ 2022-11-14 ┆ 250          │
│ 2022-11-15 ┆ 226          │
│ 2022-11-16 ┆ 267          │
│ 2022-11-17 ┆ 224          │
│ 2022-11-18 ┆ 221          │
│ 2022-11-19 ┆ 199          │
│ 2022-11-20 ┆ 199          │
│ 2022-11-21 ┆ 174          │
│ 2022-11-22 ┆ 180          │
│ 2022-11-23 ┆ 166          │
│ 2022-11-24 ┆ 150          │
│ 2022-11-25 ┆ 170          │
│ 2022-11-26 ┆ 132          │
│ 2022-11-27 ┆ 106          │
│ 2022-11-28 ┆ 129          │
│ 2022-11-29 ┆ 104          │
│ 2022-11-30 ┆ 115          │
│ 2022-12-01 ┆ 88           │
│ 2022-12-02 ┆ 85           │
│ 2022-12-03 ┆ 60           │
│ 2022-12-04 ┆ 93           │
│ 2022-12-05 ┆ 65           │
│ 2022-12-06 ┆ 47           │
│ 2022-12-07 ┆ 54           │
│ 2022-12-08 ┆ 48           │
│ 2022-12-09 ┆ 49           │
│ 2022-12-10 ┆ 29           │
│ 2022-12-11 ┆ 22           │
│ 2022-12-12 ┆ 20           │
│ 2022-12-13 ┆ 21           │
│ 2022-12-14 ┆ 23           │
│ 2022-12-15 ┆ 31           │
│ 2022-12-16 ┆ 8            │
│ 2022-12-17 ┆ 15           │
│ 2022-12-18 ┆ 14           │
│ 2022-12-19 ┆ 26           │
│ 2022-12-20 ┆ 14           │
│ 2022-12-21 ┆ 20           │
│ 2022-12-22 ┆ 14           │
│ 2022-12-23 ┆ 18           │
│ 2022-12-24 ┆ 20           │
│ 2022-12-25 ┆ 18           │
│ 2022-12-26 ┆ 14           │
│ 2022-12-27 ┆ 3            │
│ 2022-12-28 ┆ 17           │
│ 2022-12-29 ┆ 10           │
│ 2022-12-30 ┆ 5            │
│ 2022-12-31 ┆ 15           │
│ 2023-01-01 ┆ 4            │
│ 2023-01-02 ┆ 5            │
│ 2023-01-03 ┆ 8            │
│ 2023-01-04 ┆ 5            │
│ 2023-01-05 ┆ 2            │
│ 2023-01-06 ┆ 2            │
│ 2023-01-07 ┆ 1            │
│ 2023-01-08 ┆ 3            │
│ 2023-01-09 ┆ 2            │
│ 2023-01-11 ┆ 3            │
│ 2023-01-12 ┆ 2            │
└────────────┴──────────────┘

In [ ]:
'''
    Observations:
        - After 2022-11-05, we end up only seeing laundered transactions that take multiple days to pan out (https://www.kaggle.com/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml/discussion/427517)
                
    We filter the data for two main reason:
- For meaningful analysis and results, we need laundered transactions mixed in with normal transactions. Data after 2022-11-05 does not represent such data.

    --> Outcome: Filter to data up until 2022-11-05
'''

filtered_data = transaction_data.filter(pl.col("Timestamp") < pl.date(2022, 11, 6))

In [27]:
daily_transactions = (
    filtered_data
    .group_by(
        pl.col("Timestamp").dt.date().alias("Date")
    )
    .agg(
        pl.len().alias("Transactions")
    )
    .sort("Date")
    .collect()
)

daily_transactions

shape: (97, 2)
┌────────────┬──────────────┐
│ Date       ┆ Transactions │
│ ---        ┆ ---          │
│ date       ┆ u32          │
╞════════════╪══════════════╡
│ 2022-08-01 ┆ 4377581      │
│ 2022-08-02 ┆ 1894426      │
│ 2022-08-03 ┆ 1891657      │
│ 2022-08-04 ┆ 1890988      │
│ 2022-08-05 ┆ 2957130      │
│ 2022-08-06 ┆ 813056       │
│ 2022-08-07 ┆ 814101       │
│ 2022-08-08 ┆ 1891591      │
│ 2022-08-09 ┆ 1890247      │
│ 2022-08-10 ┆ 1890146      │
│ 2022-08-11 ┆ 1889967      │
│ 2022-08-12 ┆ 2568302      │
│ 2022-08-13 ┆ 814055       │
│ 2022-08-14 ┆ 812269       │
│ 2022-08-15 ┆ 1892821      │
│ 2022-08-16 ┆ 1891495      │
│ 2022-08-17 ┆ 1891691      │
│ 2022-08-18 ┆ 1891396      │
│ 2022-08-19 ┆ 2958169      │
│ 2022-08-20 ┆ 814803       │
│ 2022-08-21 ┆ 813530       │
│ 2022-08-22 ┆ 1891747      │
│ 2022-08-23 ┆ 1891491      │
│ 2022-08-24 ┆ 1890017      │
│ 2022-08-25 ┆ 1892593      │
│ 2022-08-26 ┆ 2567772      │
│ 2022-08-27 ┆ 812853       │
│ 2022-08-28 ┆ 813840       │
│ 2022-08-29 ┆ 1892065      │
│ 2022-08-30 ┆ 1890812      │
│ 2022-08-31 ┆ 4206039      │
│ 2022-09-01 ┆ 1892319      │
│ 2022-09-02 ┆ 2957375      │
│ 2022-09-03 ┆ 815386       │
│ 2022-09-04 ┆ 812832       │
│ 2022-09-05 ┆ 1894624      │
│ 2022-09-06 ┆ 1892344      │
│ 2022-09-07 ┆ 1891555      │
│ 2022-09-08 ┆ 1892299      │
│ 2022-09-09 ┆ 2568845      │
│ 2022-09-10 ┆ 814162       │
│ 2022-09-11 ┆ 814200       │
│ 2022-09-12 ┆ 1892539      │
│ 2022-09-13 ┆ 1892387      │
│ 2022-09-14 ┆ 1892965      │
│ 2022-09-15 ┆ 1891778      │
│ 2022-09-16 ┆ 2958501      │
│ 2022-09-17 ┆ 813686       │
│ 2022-09-18 ┆ 813562       │
│ 2022-09-19 ┆ 1892470      │
│ 2022-09-20 ┆ 1892491      │
│ 2022-09-21 ┆ 1893537      │
│ 2022-09-22 ┆ 1892604      │
│ 2022-09-23 ┆ 2568608      │
│ 2022-09-24 ┆ 813779       │
│ 2022-09-25 ┆ 814586       │
│ 2022-09-26 ┆ 1891428      │
│ 2022-09-27 ┆ 1891106      │
│ 2022-09-28 ┆ 1891017      │
│ 2022-09-29 ┆ 1891793      │
│ 2022-09-30 ┆ 5267847      │
│ 2022-10-01 ┆ 816642       │
│ 2022-10-02 ┆ 813867       │
│ 2022-10-03 ┆ 1892387      │
│ 2022-10-04 ┆ 1892169      │
│ 2022-10-05 ┆ 1891281      │
│ 2022-10-06 ┆ 1891587      │
│ 2022-10-07 ┆ 2569213      │
│ 2022-10-08 ┆ 814049       │
│ 2022-10-09 ┆ 815663       │
│ 2022-10-10 ┆ 1890451      │
│ 2022-10-11 ┆ 1890872      │
│ 2022-10-12 ┆ 1891654      │
│ 2022-10-13 ┆ 1891172      │
│ 2022-10-14 ┆ 2956404      │
│ 2022-10-15 ┆ 812499       │
│ 2022-10-16 ┆ 815246       │
│ 2022-10-17 ┆ 1890916      │
│ 2022-10-18 ┆ 1890654      │
│ 2022-10-19 ┆ 1891540      │
│ 2022-10-20 ┆ 1890010      │
│ 2022-10-21 ┆ 2568707      │
│ 2022-10-22 ┆ 815445       │
│ 2022-10-23 ┆ 814191       │
│ 2022-10-24 ┆ 1891308      │
│ 2022-10-25 ┆ 1890227      │
│ 2022-10-26 ┆ 1889484      │
│ 2022-10-27 ┆ 1889923      │
│ 2022-10-28 ┆ 2952853      │
│ 2022-10-29 ┆ 815539       │
│ 2022-10-30 ┆ 3175032      │
│ 2022-10-31 ┆ 1897143      │
│ 2022-11-01 ┆ 1891658      │
│ 2022-11-02 ┆ 1890072      │
│ 2022-11-03 ┆ 1889162      │
│ 2022-11-04 ┆ 2566993      │
│ 2022-11-05 ┆ 812985       │
└────────────┴──────────────┘

### Save Data

In [28]:
# Save the lazy cleaned dataset directly to CSV (streaming, low memory)
filtered_data.sink_parquet("../data/filtered_transactions.parquet")